export enum ModalTypes {
  ADD_MILEAGE = 'MODAL/ADD_MILEAGE',
  ADD_REPAIR = 'MODAL/ADD_REPAIR',
  ADD_PURCHASES = 'MODAL/ADD_PURCHASES',
  ADD_REFILL = 'MODAL/ADD_REFILL',
  ADD_CAR = 'MODAL/ADD_CAR',
}