export enum UserActionTypes {
  LOAD_USER_DATA_REQUEST = 'USER/LOAD_USER_DATA_REQUEST',
  LOAD_USER_DATA_SUCCESS = 'USER/LOAD_USER_DATA_SUCCESS',
  LOAD_USER_DATA_FAILURE = 'USER/LOAD_USER_DATA_FAILURE',
}